version: '2'

services:
  nginx-proxy:
    container_name: zeroth-ee-dashboard
    image: 161969600347.dkr.ecr.ap-northeast-2.amazonaws.com/zeroth/zeroth-ee-dashboard:1.0.0
    environment:
      - KEYCLOAK_URL=http://115.71.1.70:8888/auth
      - KEYCLOAK_REALM=zeroth
      - KEYCLOAK_CLIENT_ID=zeroth-web
      - BACKEND_URL=http://115.71.1.70:8888/api
      - HOME_URL=http://test.zeroth-ee.alabs.ai
    ports:
      - "8003:80"
    volumes:
      - ./dockerize/nginx:/etc/nginx/conf.d/
